services:

  db:
    image: postgres:17-alpine

    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

  blog:
    image: ghcr.io/prs2rnn/django-blog:latest

    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      - db

    networks:
      - default
      - web

    volumes:
      - static_data:/app/staticfiles
      - media_data:/app/media

volumes:
  postgres_data:
  static_data:
    external: true
    name: blog_static

  media_data:
    external: true
    name: blog_media

networks:
  web:
    external: true
