# Generated by Django 6.0.6 on 2026-06-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("github_url", models.URLField(blank=True, null=True)),
                ("demo_url", models.URLField(blank=True, null=True)),
                ("tech_stack", models.CharField(blank=True, max_length=300)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
