# Generated by Django 6.0.6 on 2026-06-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="project",
            name="tech_stack",
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("wip", "Work in progress"), ("done", "Finished")],
                default="done",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="techs",
            field=models.ManyToManyField(to="core.tech"),
        ),
    ]
