# Generated by Django 6.0.6 on 2026-06-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_tech_remove_project_tech_stack_project_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("wip", "Work in progress"), ("done", "Finished")],
                max_length=10,
            ),
        ),
    ]
