# Generated by Django 6.0.6 on 2026-06-13 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_project_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-created_at"]},
        ),
    ]
