# Generated by Django 6.0.6 on 2026-06-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_project_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("wip", "Work in progress"), ("done", "Finished")],
                default="done",
                max_length=10,
            ),
        ),
    ]
