# Generated by Django 6.0.6 on 2026-06-07 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_rename_posts_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"], "verbose_name": "Note"},
        ),
    ]
