# Generated by Django 6.0.6 on 2026-06-07 19:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_alter_post_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
    ]
