# Generated by Django 6.0.6 on 2026-06-11 20:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_tag_post_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ("name",)},
        ),
    ]
