# Generated by Django 6.0.6 on 2026-06-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0008_post_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.TextField(default="", max_length=120),
        ),
    ]
